### ISSUE TITLE
Ensure that agenda, connection and emergency contact info are clear to on-line participants

### ISSUE THREAD

**Issue by agropper** [FutureCommerce/Hackathon#29]
We have a  complex structure. Online participation to unconferences and hackathons is difficult. We need to pay a lot of attention to be welcoming to online participants.

**Comment by dazzaji** [comment]
- Clear and tested instruction for signup, engagement and getting questions/issues resolved.
- Connection info for EVERY AGENDA ITEM for each session.  Even those sessions with no online partic should note that factor in the SAME PLACE.
- Key contact info for online participants and projects and teams (who do you call how do you communicate ?
- Set up Slack, etc. 

Add more criteria here.
